baseURL = "https://mhelmetag.github.io"
languageCode = "en-us"
theme = "coder"
paginate = 20
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Max Helmetag"
    description = "Max Helmetag's personal website"
    keywords = "blog,developer,personal"
    info = "Avid Tinkerer && Engineer"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/mhelmetag/"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/mhelmetag/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
